# coding: utf-8

# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from appwrite_client_python_sdk.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from appwrite_client_python_sdk.model.account_complete_mfa_challenge_request import AccountCompleteMfaChallengeRequest
from appwrite_client_python_sdk.model.account_complete_password_recovery_request import AccountCompletePasswordRecoveryRequest
from appwrite_client_python_sdk.model.account_confirm_phone_verification_request import AccountConfirmPhoneVerificationRequest
from appwrite_client_python_sdk.model.account_create_email_password_session_request import AccountCreateEmailPasswordSessionRequest
from appwrite_client_python_sdk.model.account_create_email_token_request import AccountCreateEmailTokenRequest
from appwrite_client_python_sdk.model.account_create_email_verification_request import AccountCreateEmailVerificationRequest
from appwrite_client_python_sdk.model.account_create_email_verification_request1 import AccountCreateEmailVerificationRequest1
from appwrite_client_python_sdk.model.account_create_magic_url_token_request import AccountCreateMagicUrlTokenRequest
from appwrite_client_python_sdk.model.account_create_mfa_challenge_request import AccountCreateMfaChallengeRequest
from appwrite_client_python_sdk.model.account_create_password_recovery_request import AccountCreatePasswordRecoveryRequest
from appwrite_client_python_sdk.model.account_create_phone_token_request import AccountCreatePhoneTokenRequest
from appwrite_client_python_sdk.model.account_create_push_target_request import AccountCreatePushTargetRequest
from appwrite_client_python_sdk.model.account_create_session_from_token_request import AccountCreateSessionFromTokenRequest
from appwrite_client_python_sdk.model.account_delete_authenticator_request import AccountDeleteAuthenticatorRequest
from appwrite_client_python_sdk.model.account_register_user_request import AccountRegisterUserRequest
from appwrite_client_python_sdk.model.account_update_magic_url_session_request import AccountUpdateMagicUrlSessionRequest
from appwrite_client_python_sdk.model.account_update_mfa_status_request import AccountUpdateMfaStatusRequest
from appwrite_client_python_sdk.model.account_update_name_operation_request import AccountUpdateNameOperationRequest
from appwrite_client_python_sdk.model.account_update_password_request import AccountUpdatePasswordRequest
from appwrite_client_python_sdk.model.account_update_phone_request import AccountUpdatePhoneRequest
from appwrite_client_python_sdk.model.account_update_phone_session_request import AccountUpdatePhoneSessionRequest
from appwrite_client_python_sdk.model.account_update_preferences_request import AccountUpdatePreferencesRequest
from appwrite_client_python_sdk.model.account_update_push_target_request import AccountUpdatePushTargetRequest
from appwrite_client_python_sdk.model.account_update_user_email_request import AccountUpdateUserEmailRequest
from appwrite_client_python_sdk.model.account_verify_authenticator_request import AccountVerifyAuthenticatorRequest
from appwrite_client_python_sdk.model.algo_argon2 import AlgoArgon2
from appwrite_client_python_sdk.model.algo_bcrypt import AlgoBcrypt
from appwrite_client_python_sdk.model.algo_md5 import AlgoMd5
from appwrite_client_python_sdk.model.algo_phpass import AlgoPhpass
from appwrite_client_python_sdk.model.algo_scrypt import AlgoScrypt
from appwrite_client_python_sdk.model.algo_scrypt_modified import AlgoScryptModified
from appwrite_client_python_sdk.model.algo_sha import AlgoSha
from appwrite_client_python_sdk.model.any import Any
from appwrite_client_python_sdk.model.continent import Continent
from appwrite_client_python_sdk.model.continent_list import ContinentList
from appwrite_client_python_sdk.model.country import Country
from appwrite_client_python_sdk.model.country_list import CountryList
from appwrite_client_python_sdk.model.currency import Currency
from appwrite_client_python_sdk.model.currency_list import CurrencyList
from appwrite_client_python_sdk.model.databases_create_document_request import DatabasesCreateDocumentRequest
from appwrite_client_python_sdk.model.databases_create_document_request_permissions import DatabasesCreateDocumentRequestPermissions
from appwrite_client_python_sdk.model.databases_update_document_by_id_request import DatabasesUpdateDocumentByIdRequest
from appwrite_client_python_sdk.model.databases_update_document_by_id_request_permissions import DatabasesUpdateDocumentByIdRequestPermissions
from appwrite_client_python_sdk.model.document import Document
from appwrite_client_python_sdk.model.document_list import DocumentList
from appwrite_client_python_sdk.model.documentpermissions import Documentpermissions
from appwrite_client_python_sdk.model.error import Error
from appwrite_client_python_sdk.model.execution import Execution
from appwrite_client_python_sdk.model.execution_list import ExecutionList
from appwrite_client_python_sdk.model.executionpermissions import Executionpermissions
from appwrite_client_python_sdk.model.file import File
from appwrite_client_python_sdk.model.file_list import FileList
from appwrite_client_python_sdk.model.filepermissions import Filepermissions
from appwrite_client_python_sdk.model.functions_trigger_function_execution_request import FunctionsTriggerFunctionExecutionRequest
from appwrite_client_python_sdk.model.headers import Headers
from appwrite_client_python_sdk.model.identity import Identity
from appwrite_client_python_sdk.model.identity_list import IdentityList
from appwrite_client_python_sdk.model.jwt import Jwt
from appwrite_client_python_sdk.model.language import Language
from appwrite_client_python_sdk.model.language_list import LanguageList
from appwrite_client_python_sdk.model.locale import Locale
from appwrite_client_python_sdk.model.locale_code import LocaleCode
from appwrite_client_python_sdk.model.locale_code_list import LocaleCodeList
from appwrite_client_python_sdk.model.log import Log
from appwrite_client_python_sdk.model.log_list import LogList
from appwrite_client_python_sdk.model.membership import Membership
from appwrite_client_python_sdk.model.membership_list import MembershipList
from appwrite_client_python_sdk.model.membership_roles import MembershipRoles
from appwrite_client_python_sdk.model.messaging_add_new_subscriber_request import MessagingAddNewSubscriberRequest
from appwrite_client_python_sdk.model.mfa_challenge import MfaChallenge
from appwrite_client_python_sdk.model.mfa_factors import MfaFactors
from appwrite_client_python_sdk.model.mfa_recovery_codes import MfaRecoveryCodes
from appwrite_client_python_sdk.model.mfa_recovery_codes_recovery_codes import MfaRecoveryCodesRecoveryCodes
from appwrite_client_python_sdk.model.mfa_type import MfaType
from appwrite_client_python_sdk.model.phone import Phone
from appwrite_client_python_sdk.model.phone_list import PhoneList
from appwrite_client_python_sdk.model.preferences import Preferences
from appwrite_client_python_sdk.model.session import Session
from appwrite_client_python_sdk.model.session_factors import SessionFactors
from appwrite_client_python_sdk.model.session_list import SessionList
from appwrite_client_python_sdk.model.storage_create_file_request import StorageCreateFileRequest
from appwrite_client_python_sdk.model.storage_create_file_request_permissions import StorageCreateFileRequestPermissions
from appwrite_client_python_sdk.model.storage_update_file_by_id_request import StorageUpdateFileByIdRequest
from appwrite_client_python_sdk.model.storage_update_file_by_id_request_permissions import StorageUpdateFileByIdRequestPermissions
from appwrite_client_python_sdk.model.subscriber import Subscriber
from appwrite_client_python_sdk.model.subscriber_target import SubscriberTarget
from appwrite_client_python_sdk.model.target import Target
from appwrite_client_python_sdk.model.team import Team
from appwrite_client_python_sdk.model.team_list import TeamList
from appwrite_client_python_sdk.model.team_prefs import TeamPrefs
from appwrite_client_python_sdk.model.teams_create_membership_request import TeamsCreateMembershipRequest
from appwrite_client_python_sdk.model.teams_create_membership_request_roles import TeamsCreateMembershipRequestRoles
from appwrite_client_python_sdk.model.teams_create_new_team_request import TeamsCreateNewTeamRequest
from appwrite_client_python_sdk.model.teams_create_new_team_request_roles import TeamsCreateNewTeamRequestRoles
from appwrite_client_python_sdk.model.teams_update_membership_roles_request import TeamsUpdateMembershipRolesRequest
from appwrite_client_python_sdk.model.teams_update_membership_roles_request_roles import TeamsUpdateMembershipRolesRequestRoles
from appwrite_client_python_sdk.model.teams_update_membership_status_request import TeamsUpdateMembershipStatusRequest
from appwrite_client_python_sdk.model.teams_update_name_by_id_request import TeamsUpdateNameByIdRequest
from appwrite_client_python_sdk.model.teams_update_prefs_by_id_request import TeamsUpdatePrefsByIdRequest
from appwrite_client_python_sdk.model.token import Token
from appwrite_client_python_sdk.model.user import User
from appwrite_client_python_sdk.model.user_hash_options import UserHashOptions
from appwrite_client_python_sdk.model.user_labels import UserLabels
from appwrite_client_python_sdk.model.user_prefs import UserPrefs
