# coding: utf-8

"""
    Appwrite

    Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

    The version of the OpenAPI document: 1.5.0
    Contact: team@appwrite.io
    Created by: https://appwrite.io/support
"""

from appwrite_client_python_sdk.paths.databases_database_id_collections_collection_id_documents.post import CreateDocumentRaw
from appwrite_client_python_sdk.paths.databases_database_id_collections_collection_id_documents_document_id.delete import DeleteDocumentByIdRaw
from appwrite_client_python_sdk.paths.databases_database_id_collections_collection_id_documents_document_id.get import GetDocumentByIdRaw
from appwrite_client_python_sdk.paths.databases_database_id_collections_collection_id_documents.get import ListUserDocumentsRaw
from appwrite_client_python_sdk.paths.databases_database_id_collections_collection_id_documents_document_id.patch import UpdateDocumentByIdRaw


class DatabasesApiRaw(
    CreateDocumentRaw,
    DeleteDocumentByIdRaw,
    GetDocumentByIdRaw,
    ListUserDocumentsRaw,
    UpdateDocumentByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
