# coding: utf-8

"""
    Appwrite

    Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

    The version of the OpenAPI document: 1.5.0
    Contact: team@appwrite.io
    Created by: https://appwrite.io/support
"""

from appwrite_client_python_sdk.paths.functions_function_id_executions_execution_id.get import GetExecutionLogRaw
from appwrite_client_python_sdk.paths.functions_function_id_executions.get import ListExecutionsRaw
from appwrite_client_python_sdk.paths.functions_function_id_executions.post import TriggerFunctionExecutionRaw


class FunctionsApiRaw(
    GetExecutionLogRaw,
    ListExecutionsRaw,
    TriggerFunctionExecutionRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
